version: '3'

services:
  db:
    container_name: db
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - asap
  
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
    networks:
      - asap
    depends_on:
      - db

networks:
  asap:

volumes:
  db_data:
